import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#9f0519",
        "on-secondary-fixed": "#003076",
        "inverse-on-surface": "#565555",
        background: "#0e0e0e",
        error: "#ff716c",
        "surface-container-highest": "#262626",
        "surface-dim": "#0e0e0e",
        outline: "#767575",
        "on-surface-variant": "#adaaaa",
        "on-secondary-container": "#f7f7ff",
        "on-tertiary-container": "#0b5800",
        "on-background": "#ffffff",
        secondary: "#6e9bff",
        "on-error-container": "#ffa8a3",
        "on-tertiary": "#0d6100",
        "on-secondary-fixed-variant": "#004baf",
        "on-surface": "#ffffff",
        "surface-container": "#1a1a1a",
        "surface-variant": "#262626",
        "on-primary-container": "#005d5d",
        "error-dim": "#d7383b",
        "on-primary-fixed-variant": "#006262",
        "secondary-fixed-dim": "#acc3ff",
        "surface-tint": "#c1fffe",
        "primary-container": "#00ffff",
        "inverse-surface": "#fcf9f8",
        "surface-bright": "#2c2c2c",
        "on-primary": "#006767",
        "surface-container-low": "#131313",
        "on-error": "#490006",
        "tertiary-fixed": "#2ff801",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#006a6a",
        "primary-dim": "#00e6e6",
        "secondary-fixed": "#c0d1ff",
        "on-secondary": "#001d4e",
        "tertiary-container": "#2ff801",
        "tertiary-dim": "#2be800",
        "primary-fixed-dim": "#00e6e6",
        "tertiary-fixed-dim": "#2be800",
        "on-primary-fixed": "#004343",
        "surface-container-high": "#20201f",
        primary: "#c1fffe",
        "outline-variant": "#484847",
        "secondary-dim": "#0f6df3",
        "on-tertiary-fixed-variant": "#0d6200",
        "on-tertiary-fixed": "#064200",
        "secondary-container": "#0058ca",
        tertiary: "#8eff71",
        "primary-fixed": "#00f5f5",
        surface: "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
